version: "3.3"

services:
  mixnet_state:
    build: .
    image: mixnet-state
    labels:
      - traefik.http.middlewares.corsheader.headers.accessControlAllowOriginList=*
      - traefik.http.routers.mixnet_state.middlewares=corsheader
      - traefik.http.routers.mixnet_state.entrypoints=websecure
      - traefik.http.routers.mixnet_state.rule=Host(`isnymdown.notrustverify.ch`,`isnymup.com`)
      - traefik.http.routers.mixnet_state.tls=true
      - traefik.http.routers.mixnet_state.tls.certresolver=letsEncrypt
      - traefik.enable=true
    restart: unless-stopped
    env_file: .env
    ports:
      - "5003:5002"
    networks:
      - traefik-proxy
    volumes:
      - ./data/data.db:/data/data.db

  db:
    image: postgres
    restart: always
    env_file:
      - .db.env
    environment:
      POSTGRES_DB: mixnetstate
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval    : 1s
      timeout: 5s
      retries: 10
    volumes:
       - ./db-data/:/var/lib/postgresql/data/

networks:
   traefik-proxy:
      external: true

